### ISSUE TITLE
Question 586: BC

### ISSUE THREAD

**Issue by SUN-Xiaoying** [Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C01-Practice-Tests-Exams-Questions-Answers#12]
Option D is not an advantage because AWS usually involves pay-as-you-go pricing, which reduces the need for significant upfront capital expenditures.

**Comment by danieldanielecki** [comment]
Fixed in https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C01-Practice-Tests-Exams-Questions-Answers/commit/5c7a4ecf503b0e93e657154b5297ef178a36ead5, additionally added similar question https://github.com/Ditectrev/Amazon-Web-Services-AWS-Certified-Cloud-Practitioner-CLF-C01-Practice-Tests-Exams-Questions-Answers/commit/d9c03b7aa40876c25e69567e6b027885a0ddda84

**Comment by danieldanielecki** [comment]
Thank you @SUN-Xiaoying!
